

sqlserver_connection2:
  source: sqlserver
  name: sqlserver_connection2
  user: jeevan.v
  password: experion@123
  server: JEEVANV\SQLEXPRESS
  localhost: None
  database: AdventureWorksLT2022
  schema: SalesLT

csv_connection:
  source: csv
  name: csv_connection

parquet_connection:
  source: parquet
  name: parquet_connection